# Generated by Django 3.0.3 on 2020-02-12 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('havenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('providers', models.IntegerField(default=0)),
                ('seekers', models.IntegerField(default=0)),
                ('seek_mentor', models.BooleanField(default=False)),
                ('provide_mentor', models.BooleanField(default=False)),
                ('seek_advice', models.BooleanField(default=False)),
                ('provide_advice', models.BooleanField(default=False)),
                ('find_friends', models.BooleanField(default=False)),
                ('socialize', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havenapp.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='havenapp.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
