# Generated by Django 3.0.2 on 2020-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
