# Generated by Django 2.0.3 on 2019-11-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haven',
        ),
    ]
