# Generated by Django 2.0.3 on 2019-11-26 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0004_auto_20191126_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 6, 46, 57, 521485, tzinfo=utc)),
        ),
    ]
