# Generated by Django 2.2.10 on 2020-03-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0004_track_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
