# Generated by Django 2.2.10 on 2020-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0005_update_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal user'), (2, 'Searching for group'), (3, 'Matched with new group')], default=2),
        ),
    ]
