# Generated by Django 2.2.7 on 2020-01-14 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0005_auto_20191126_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 22, 15, 6, 362729, tzinfo=utc)),
        ),
    ]
