# Generated by Django 2.2.10 on 2020-03-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0003_chat'),
        ('havenapp', '0006_update_profile_status_col'),
    ]

    operations = [
    ]
