# Generated by Django 2.2.7 on 2020-01-16 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0006_auto_20200114_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 17, 27, 21, 709654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
