# Generated by Django 2.2.10 on 2020-03-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0006_update_profile_status_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='matched_group',
            field=models.UUIDField(null=True),
        ),
    ]
