# Generated by Django 2.2.10 on 2020-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0007_merge_20200303_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='join_date',
            new_name='chat_time',
        ),
    ]
