# Generated by Django 2.2.10 on 2020-03-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0007_added_new_values_to_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
