# Generated by Django 2.2.10 on 2020-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0008_auto_20200303_2054'),
        ('havenapp', '0008_removed_location_from_profile'),
    ]

    operations = [
    ]
