# Generated by Django 2.2.10 on 2020-03-05 00:48

from django.db import migrations, models
import havenapp.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0009_profile_pic_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=havenapp.models.profile.get_upload_to),
        ),
    ]
