# Generated by Django 2.2.10 on 2020-03-04 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0010_savedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='react',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedmessages',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
