# Generated by Django 2.2.10 on 2020-03-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0011_auto_20200304_0230'),
        ('havenapp', '0010_profile_pic_changes'),
    ]

    operations = [
    ]
