# Generated by Django 2.2.10 on 2020-03-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0012_merge_20200305_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_time',
            field=models.DateTimeField(),
        ),
    ]
