# Generated by Django 2.2.10 on 2020-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0013_auto_20200305_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmessages',
            name='group_id',
            field=models.TextField(),
        ),
    ]
