# Generated by Django 2.2.10 on 2020-03-11 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('havenapp', '0015_group_table_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmessages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='havenapp.Chat'),
        ),
        migrations.AlterField(
            model_name='savedmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
