# Generated by Django 2.0.3 on 2019-11-26 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('havenapp', '0002_delete_haven'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 6, 30, 8, 721796))),
                ('active', models.BooleanField()),
            ],
        ),
    ]
